[package]
name = "ptr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
colored = "2.1.0"
home = "0.5.9"
reqwest = { version = "0.12.5", features = ["blocking", "json", "stream"] }
serde = { version = "1.0.207", features = ["derive"] }
tabwriter = { version = "1.4.0", features = ["ansi_formatting"] }
toml = "0.8.19"
zip = { version = "2.1.6", default-features = false, features = ["deflate"] }
