name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-upload:
    name: release ${{ matrix.target }} ${{ matrix.feature }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          feature: sudo
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          feature: sudo
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          feature: winapi
        - target: aarch64-pc-windows-msvc
          os: windows-latest
          feature: winapi

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}

    - name: Run Cargo
      run: |
        if ($env:matrix_feature -eq "sudo") {
          cargo build --release --target $env:matrix_target
        } else {
          cargo build --release --target $env:matrix_target --features $env:matrix_feature
        }

    - name: Archive
      run: 7z a "ptr-${{ matrix.target }}-${{ matrix.feature }}.zip" README.md LICENSE ./target/${{ matrix.target }}/release/ptr.exe

    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "ptr-${{ matrix.target }}-${{ matrix.feature }}.zip"
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true